Update EaglercraftVersion.java to signify that this is a community fork
Eagler-CE/repo pull request #4
Opened 2023-09-16 01:49 UTC by OtterCodes102

also add repo link

2023-09-16 02:33 UTC, literally1984 requested changes
wtf is a review

2023-09-16 02:33 UTC, literally1984 commented on sources/main/java/net/lax1dude/eaglercraft/v1_8/EaglercraftVersion.java
> -			projectOriginRevision + "-" + projectOriginVersion + " ultimate";
I don't know too much about the eagler source code but I'm pretty sure this was meant to be kept a variable... To change the version why not just change projectOriginVersion instead 🙂

2023-09-16 06:58 UTC, wxnnvs commented on sources/main/java/net/lax1dude/eaglercraft/v1_8/EaglercraftVersion.java
> -			projectOriginRevision + "-" + projectOriginVersion + " ultimate";
It doesn't matter here, it's just a string being displayed

2023-09-16 14:06 UTC, OtterCodes102 commented
aight i can do that if you want

2023-09-16 17:50 UTC, literally1984 commented on sources/main/java/net/lax1dude/eaglercraft/v1_8/EaglercraftVersion.java
> -			projectOriginRevision + "-" + projectOriginVersion + " ultimate";
> It doesn't matter here, it's just a string being displayed

Actually no, projectOriginVersion should be used because it also used in the connection handshake to servers, as can be seen here: https://github.com/Eagler-CE/repo/blob/d20e329f6eecb20d969a60d1250679c7a15758a6/sources/main/java/net/lax1dude/eaglercraft/v1_8/socket/ConnectionHandshake.java#L69

2023-09-16 17:52 UTC, literally1984 approved these changes

2023-09-16 22:54 UTC, vukle commented
seems good to merge, @NuraadGit anything before i merge?

2023-09-17 20:52 UTC, vukle commented
24 hours have passed, merging now.

2023-09-17 20:53 UTC, merged

2023-09-19 11:43 UTC, NuraadGit commented
gay, you could have asked me on discord

2023-09-19 14:34 UTC, vukle commented
> gay, you could have asked me on discord

just check git feed